# Generated by Django 5.2.4 on 2025-08-05 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
        ('products', '0011_alter_productbrands_slug_alter_productcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_basket', to='products.products'),
        ),
    ]
