# Generated by Django 5.2.4 on 2026-08-09 10:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0003_alter_order_is_paid_alter_order_payment_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('is_paid', False)), fields=('user',), name='unique_active_order_per_user'),
        ),
    ]
