# Generated by Django 5.2.4 on 2026-08-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0004_order_unique_active_order_per_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_authority',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
