# Generated by Django 5.2.4 on 2026-08-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0005_order_payment_authority'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_amount',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
