# Generated by Django 5.2.4 on 2026-08-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0006_order_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
