# Generated by Django 5.2.4 on 2026-08-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0007_order_payment_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
