# Generated by Django 5.2.4 on 2026-08-18 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0008_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_ref_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
