# Generated by Django 5.2.4 on 2026-08-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0009_order_payment_ref_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_status',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
