# Generated by Django 5.2.4 on 2025-07-18 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBrands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('url_title', models.CharField(db_index=True, max_length=200)),
                ('is_delete', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('url_title', models.CharField(db_index=True, max_length=200)),
                ('is_delete', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/products')),
                ('main_price', models.IntegerField()),
                ('discount_price', models.IntegerField(blank=True, null=True)),
                ('short_description', models.CharField(blank=True, db_index=True, max_length=300, null=True)),
                ('main_description', models.TextField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('in_stock', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField()),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productbrands')),
                ('category', models.ManyToManyField(related_name='product_categories', to='products.productcategory')),
            ],
        ),
    ]
