# Generated by Django 5.2.4 on 2025-07-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_options_productgallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbrands',
            name='is_delete',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='is_delete',
            field=models.BooleanField(default=True),
        ),
    ]
