# Generated by Django 5.2.4 on 2025-07-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productbrands_is_delete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbrands',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
