# Generated by Django 5.2.4 on 2025-07-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productbrands_is_delete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='url_title',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
