# Generated by Django 5.2.4 on 2025-07-27 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_products_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productbrands',
            old_name='url_title',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='url_title',
            new_name='slug',
        ),
    ]
