# Generated by Django 5.2.4 on 2025-08-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_rename_url_title_productbrands_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='is_delete',
        ),
        migrations.AddField(
            model_name='products',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
