# Generated by Django 5.2.4 on 2025-08-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_products_is_delete_products_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='is_active',
        ),
        migrations.AddField(
            model_name='products',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
