# Generated by Django 5.2.4 on 2025-08-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_products_is_active_products_is_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbrands',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
